### ISSUE TITLE
Tweak tests to run against various Python versions (py3 should be supported already)

### ISSUE THREAD

**Issue by voutilad** [freelawproject/reporters-db#11]
Some minor changes needed, but adding Python 3 support (ideally 3.6 as it's the latest stable) will remove yet another Python 2.7-only dependency from CourtListener.

I have a local branch so far passing tests with CPython 3.6. Need to also:
- update metadata for PyPI
- update Travis file
- maybe add Tox testing support for executing test suite on multiple Python versions

**Comment by voutilad** [comment]
See PR #12

**Comment by mlissner** [comment]
Just found this issue from a couple years ago. Looks like we just need to start running our tests on all versions and we can declare Py3 compatibility.

**Comment by mlissner** [comment]
2.7 is dropped, and we test on a few 3.x versions. All set here.
