### ISSUE TITLE
Recognizing Public Law Citations

### ISSUE THREAD

**Issue by bbernicker** [freelawproject/reporters-db#116]
Until a federal statute has been codified, the correct citation to it uses both its public/private law number and its location in the statutes at large. R16.1.5.  Until a federal statute has been published in the statutes at large (at the end of the Congressional session), the correct citation is to the public/private law number alone.

When given a citation in this form, Eyecite recognizes the statutes at large citation but not the public/private law citation. For example:
```
text = "Patient Protection and Affordable Care Act, Pub. L. No. 111-148, § 1101, 124 Stat. 119, 141-43 (2010)"
print(get_citations(text))
>> [UnknownCitation('§', metadata=CitationBase.Metadata(parenthetical=None)), FullLawCitation('124 Stat. 119', groups={'volume': '124', 'reporter': 'Stat.', 'page': '119'}, metadata=FullLawCitation.Metadata(parenthetical=None, pin_cite=None, year=None, publisher=None, day=None, month=None))]
```
We should be able to detect the public/private law citation, and I am working on adding support for it now.

**Comment by flooie** [comment]
this is great.  And fascinating thank you.
