### ISSUE TITLE
Enhancement to eyecite benchmark

### ISSUE THREAD

**Issue by flooie** [freelawproject/reporters-db#123]
Should generate comment in PR that eyecite benchmark is running.  Currently it triggers a PR comment only after it has executed 
completely in eyecite, but the command looks complete in reporters-db because it just triggers the execution in eyecite.

**Comment by flooie** [comment]
I would suggest a ... hold tight, the Eyecite test is running comment that overwrites anything in the PR until it is updated... that way we know to wait.

**Comment by mlissner** [comment]
Is it hard for the eyecite report to use the same comment as this one? So:

1. PR created
2. Reporters-db CI runs, dispatches to eyecite, creates comment number 2 that says, "Hold tight...", (and links to the action?)
3. Eyecite action runs, updates comment number 2 on that PR

I think this is how dependabot does it, for example. If you push code to a dependabot PR, it'll update it's first comment to say, "Regenerating..." and then it'll update the comment again when the regenerated comment is ready.

I don't know that we need that level of polish, but it's the UX I've seen.

**Comment by flooie** [comment]
not hard at all.

**Comment by flooie** [comment]
There is some weirdness coming out of reporters-db and the eyecite benchmark these days.

The section/laws finds have extra whitespace in them that isn't being normalized.  Or perhaps our whitespace is too broad.  Allowing all whitespace may have been a bridge too far.  

This at the least breaks the markdown tables

**Comment by flooie** [comment]
Secondly, it seems to be using older commits to run against now instead of the most recent one.  Not sure what is going on here.

**Comment by flooie** [comment]
Clearly, eyecite when it generates the benchmark is not installing the most up to date reporters-db but whatever is locked into the poetry lock file.  This seems like it should be easy to fix by updating or forcing the most up to date version of reporters-db and then installing the branch.   

I will test this fix later today.

**Comment by flooie** [comment]
<img width="971" alt="Screen Shot 2022-09-11 at 10 42 43 AM" src="https://user-images.githubusercontent.com/6464529/189533722-707eb5fb-1797-469a-81ec-4160a044178d.png">

**Comment by flooie** [comment]
This is updated.  

As well as the bug that was plaguing the reporters-db eyecite report that was showing older versions of reporters-db

**Comment by mlissner** [comment]
Cool!

**Comment by mlissner** [comment]
FYI, I added a link to the comment. I don't think it should affect anything, but I also didn't test it! If things break and I'm traveling, you can curse me and you'll know why. (Sorry, if so.)

**Comment by flooie** [comment]
Thanks.
