### ISSUE TITLE
Add Law Journal Abbreviations

### ISSUE THREAD

**Issue by mlissner** [freelawproject/reporters-db#13]
We were recently sent the attached CSV of law journal abbreviations. I'm not sure how these would fit in with the reporters-db, but they certainly do somehow. 

This CSV, therefore, needs to get converted, and it needs to get added as a JSON object or similar. It's good stuff.
[LawJournalAbbreviations.xlsx](https://github.com/freelawproject/reporters-db/files/1092912/LawJournalAbbreviations.xlsx)

**Comment by fbennett** [comment]
Here is the abbrevs list used in the Juris-M abbreviation filter. Haven't touched it in yonks, not sure what it's based on, but whatever the source, they are standard abbreviations used in legal publishing. It looks like two streams have been mixed in the list, unfortunately: it contains both proper journal abbreviations, and common abbreviations of words and phrases.

Might be useful as a cross-check for the first list, and there are likely some additional titles in there as well.

[jurism-abbrevs.zip](https://github.com/freelawproject/reporters-db/files/1093001/jurism-abbrevs.zip)

**Comment by mlissner** [comment]
Oof. There's over 1,000 lines in this CSV, @fbennett. I guess it'll be useful as a cross-check, like you say, but dang if it isn't going to be a pain separating out the other stuff. I guess pulling out one-word abbreviations would be a start.

**Comment by fbennett** [comment]
How like you this, @mlissner?
[jurism-abbrevs-2.zip](https://github.com/freelawproject/reporters-db/files/1093667/jurism-abbrevs-2.zip)
 (I found a file with only the phrases in it, and filtered)

**Comment by mlissner** [comment]
Now we're talking, @fbennett ! Here's a merged version. Just needs to be JSON (probably) and we're in business.


[LawJournalAbbreviations-merged.xlsx](https://github.com/freelawproject/reporters-db/files/1093711/LawJournalAbbreviations-merged.xlsx)

**Comment by fbennett** [comment]
Oh, quick! I was about to do something about near-misses (most of which seemed to turn on straight-vs-curly apostrophe), but it looks like you've already adjusted for that in the merge.

**Comment by mlissner** [comment]
Yeah, I think so. The curlies caused mojibake, so I just found and replaced them until they were dead.
