### ISSUE TITLE
Is *anybody* using mlz_jurisdiction?

### ISSUE THREAD

**Issue by mlissner** [freelawproject/reporters-db#130]
It was originally added by @fbennett, but I don't know if anybody ever used it. I've always struggled to know what to put into it so that it can be consistent and useful. A recent PR just left it blank because they didn't know what to put in there, so it's causing at least a little friction.

I can be overly aggressive about removing unused code, but Frank, are you using this field? It is of value to you? If not, I propose we remove it and do a minor version bump with good release notes.

**Comment by bbernicker** [comment]
I use mlz_jurisdiction a little bit to feed citations detected from Eyecite into @fbennett's wonderful Jurism software. When it works it is great, but reporters-db / Eyecite have different needs than Jurism and I have found that the field is only really useful when the reporter uniquely identifies the jurisdiction of all of the authorities in it (e.g. the U.S. Reports or the Statutes at Large). Unless anybody has a use-case for which it is important to know all of the jurisidctions for all authorities that might possibly be in a reporter, I would suggest making this field optional and encouraging people to use it where the source uniquely identifies the jurisdiction of the authorities it includes.

**Comment by mlissner** [comment]
Interesting. Where I've always struggled is understanding how to make these strings so that they're actually useful. Like, what format do they take? What's the schema or data model? Is that documented somewhere in JurisM?

**Comment by flooie** [comment]
I'm just going to drop the [link to JurisM](https://juris-m.github.io/#) into the chat because I hadn't looked at this before.

**Comment by mlissner** [comment]
> I'm just going to drop the [link to JurisM](https://juris-m.github.io/#) into the chat because I hadn't looked at this before.

Think Zotero, but with legal stuff and support for i18n, if that helps.

**Comment by flooie** [comment]
Is this just an attempt to see how many more things I'll link to?

**Comment by mlissner** [comment]
Sorry, Zotero is kind of like Mendeley.

**Comment by bbernicker** [comment]
> Interesting. Where I've always struggled is understanding how to make these strings so that they're actually useful. Like, what format do they take? What's the schema or data model? Is that documented somewhere in JurisM?

Yes I also find the formatting confusing sometimes. There is a schema at [https://github.com/Juris-M/legal-resource-registry/tree/master/src](in the Legal Resource Registry). Each of those files corresponds to a country and contains a list of authorities/jurisdictions in the country with their Jurism identifier, their full name, a standard abbreviation, and some other information. As @jcushman pointed out in #58 , it would not be too challenging to update our standard tests to confirm that the values in this field correspond to valid MLZ jurisdictions. 

Where are reporter is specific to a jurisdiction (such as a state) or particular authority (a single court), I do think it is helpful to include that information in reporters-DB. It may also be helpful to include mlz_jurisdiction where there are only a few authorities included in that reporter (e.g. the N.E. reporter includes cases from 5 states). But I cannot think of any purpose for including mlz_jurisdiction where are reporter reports cases (or documents other than cases) associated with a wide range of jurisdictions, such as a wide range of treaties between and among all the countries of the world.

**Comment by mlissner** [comment]
OK, so it seems people care about mlz_jurisdiction and it's used, so let's just shut this down and focus our energy back to #58. Closing for now.
