### ISSUE TITLE
Handle citations with N.M. (Ct. App.) reporter

### ISSUE THREAD

**Issue by quevon24** [freelawproject/reporters-db#140]
There are many citations left to be fixed from the reporter: “N.M. (Ct. App.)”, 157 to be exact.

This is the full list:
[n.m. ct. app. citations.csv](https://github.com/freelawproject/reporters-db/files/9882632/n.m.ct.app.citations.csv)

The problem with these citations is that if you check those cases in case.law you can see that they removed N.M. (Ct. App.) to use NMCA in the official citation.

Here is an example:

In this IA case: https://ia903001.us.archive.org/12/items/law.free.cap.nm-ct-app.1/1.4188313.json

We have these citations:
`[{"type": "official", "cite": "1 N.M. (Ct. App.) 1"}, {"type": "parallel", "cite": "2011-NMCA-108"}]`

But if you look to case.law (https://api.case.law/v1/cases/4188313/) you can find that they only have “2011-NMCA-108” as the official citation, they removed completely N.M. (Ct. App.) in the citations.

Also, if you take a look to the PDF file you will see that “2011-NMCA-108” is used instead of 1 N.M. (Ct. App.) 1. (https://cite.case.law/pdf/4188313/Prather%20v.%20Lyons,%202011-NMCA-108%20(2011).pdf)

I think that both citations refer to New Mexico Court of Appeals, but one is the old citation format using volume number, reporter abbreviation and page number, and the other is the new citation format.

I found out that New Mexico adopted a citation format that is not based on the case’s location in a reporter, instead it uses the year the case was decided, the court that decided the case and the ordinal number of the case. Check (https://libguides.law.unm.edu/MSL/citation) and (https://law.resource.org/pub/us/code/blue/IndigoBook.html)

It is not to my complete understanding but this document could be useful: https://supremecourt.nmcourts.gov/wp-content/uploads/sites/3/2022/03/Rule-23-112-NMRA-1.pdf

Maybe we can add "N.M. (Ct. App.)" as a variation.

What do you suggest to fix this?  

@flooie

**Comment by flooie** [comment]
this is great @quevon24 

I'm surprised we didn't have the original NM Ct. of Appeals citation format, but it is certainly not a variation of the `-NMCA-` 
The New Mexico Judiciary adopted neutral citations, where they use [YEAR] NMCA [SEQUENCE ORDER].  

Here we simply want to add NM Ct App as its own reporter.
