### ISSUE TITLE
Add named captured groups regexes to reporters-db

### ISSUE THREAD

**Issue by flooie** [freelawproject/reporters-db#17]
See example below
```
"regex": "(?P<reporter>T\.\s?C\.\s?Memo)\s+(?P<volume>\d{1,2})-(?P<page>\d{1,3})"

match = re.match(my_regex, some_string)
reporter = match.group('reporter')
volume = match.group('volume')
page = match.group('page')
```

**Comment by mlissner** [comment]
One challenge I'm noticing on second look is that we'll be repeating all the variations in the regex, but perhaps that's OK if this is only used for weird citations.

**Comment by mlissner** [comment]
I think this is done too. We support this now, even if we're not using it too much yet.
