### ISSUE TITLE
Record reporters that use non-standard formats like hyphens?

### ISSUE THREAD

**Issue by jcushman** [freelawproject/reporters-db#25]
For citation extraction, some reporters use non standard patterns instead of `<volume> <reporter> <page>`. The ones I know of are all neutral citation formats that use hyphens:

* `2015-Ohio-3368`
* `2000-NMCA-005`
* `1999-NMSC-013`

Does it make sense to have some way to record these special cases, e.g. as regular expressions? CAP is going to end up building up a translation table of reporter string -> regex internally, but I don't know if that has a place in reporters-db itself.

**Comment by flooie** [comment]
@jcushman - We have in fact already integrated regexes into the reporters-db for non standard patterns.  In fact, our citation matching code defaults to the regex pattern if its available in reporters-db.  

Although I think we only have ~20 reporters w/ regex patterns we would love to build it up. 

Link to [`TC Summary Opinions`](https://github.com/freelawproject/reporters-db/blob/edb779c6aa3349f99c9df0d46986a0a2f4cb47b9/reporters_db/data/reporters.json#L12806-L12808)

**Comment by jcushman** [comment]
Ah, cool, that works!

**Comment by mlissner** [comment]
The system is working!
