### ISSUE TITLE
F.Supp.3d

### ISSUE THREAD

**Issue by speedplane** [freelawproject/reporters-db#3]
As of March 2014, West released F.Supp.3d:
https://scholar.google.com/scholar_case?case=17214505910553444763&q=1+F.+Supp.+3d+1&hl=en&as_sdt=6,33

However, there appears to be some overlap with F.Supp.2d. The last case I found was decided in August:
https://scholar.google.com/scholar_case?case=16119727256826488842&q=%22999+F.+Supp.+2d%22+&hl=en&scisbd=2&as_sdt=6,33&as_ylo=2014&as_yhi=2014

The following case, despite having a higher page number, was decided in July 2014:
https://scholar.google.com/scholar_case?case=767169687770523142&q=%22999+F.+Supp.+2d%22+&hl=en&scisbd=2&as_sdt=6,33&as_ylo=2014&as_yhi=2014

**Comment by mlissner** [comment]
Thanks. Fixed!
