### ISSUE TITLE
Automated tests not running on PRs

### ISSUE THREAD

**Issue by mlissner** [freelawproject/reporters-db#30]
@flooie, can you take a look at this? I just noticed in #29 that tests are running on PRs. Not good!

**Comment by flooie** [comment]
Reporters-db now comes with tests on PRs.

<img width="974" alt="Screen Shot 2021-01-05 at 4 19 09 PM" src="https://user-images.githubusercontent.com/6464529/103700088-ef529e80-4f71-11eb-98ba-9b5894e8f9ec.png">
