### ISSUE TITLE
Add custom regexes for Tax Court reporters

### ISSUE THREAD

**Issue by mattdahl** [freelawproject/reporters-db#57]
The Tax Court reporters need custom regexes to handle their volume/reporter/page arrangements. For example, sometimes tax court citations have pages bounded by parentheses, e.g., `140 UNITED STATES TAX COURT REPORTS (200)`. Other examples are in the `working_citation*` files here: https://github.com/freelawproject/courtlistener/tree/master/cl/cleanup/test_assets

**Comment by jcushman** [comment]
Ah cool, maybe you can shed some light over in #42.

That particular example is the only one I know of that isn't currently supported, and it's a weird one. Are we sure that it's really used in citations and not just in page headers or something?

**Comment by flooie** [comment]
Without that regex we wouldn't be able to add citations to the tax court opinions because (if memory serves)... tax court is the rare court where we parse the document for the citations using juriscraper.

**Comment by mattdahl** [comment]
Lol, I searched for existing issues but missed that open PR!

**Comment by mlissner** [comment]
Dup of #42
