### ISSUE TITLE
pypi source release does not include requirements.txt and will thus fail

### ISSUE THREAD

**Issue by step21** [freelawproject/reporters-db#64]
When building for conda-forge, I noticed that the requirements.txt is not shipped, but sourced from setup.py, and thus the manual install will fail. Could this be fixed? Alternatively, I could use the github release as this has the requirements.txt but we try to match pypi and thus take releases from there.

**Comment by flooie** [comment]
You'll have to forgive me lack of knowledge around anaconda.  What would need to change to make this work for you?

**Comment by step21** [comment]
Well, it's not conda specific, just normally people will probably use the wheel from pypi or the git repo. Conda can use git repos or github tarballs, but for consistency with pypi packages tries to use those.
As far as I can tell, the only that would need to change is the inclusion of "requirements.txt" in the pypi source package. I know that this only includes six, so for python 3 is probably even irrelevant, but it is included and if it is not there it will fail with the following error 

```Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    with open(reqs_path) as reqs_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/user/reporters-db/requirements.txt```

**Comment by step21** [comment]
Follow up: I looked at the github action you are using for deployment, and I am not super familiar with uploading to pypi, so I am not sure why this is not included as it seems to clearly differentiate between the wheel and source.

**Comment by flooie** [comment]
We build via GitHub actions. Specifically [this one](https://github.com/casperdcl/deploy-pypi)

I'm sure we can figure something out.  Unfortunately we are in a bit of crunch today - but if you want to send a PR yourself I'm sure someone can take a look.

**Comment by flooie** [comment]
@step21 - v3.2.5 has been released on pypi. - let me know if this resolves this for you.

**Comment by step21** [comment]
Yes, this fixed it. Thanks.

**Comment by flooie** [comment]
@step21 thank you
